# gateway-service/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: gateway-service
  

  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/banking-realm
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: beneficiary-service
          uri: lb://beneficiary-service
          predicates:
            - Path=/api/beneficiaries/**
          filters:
            - name: AuthenticationFilter

        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/api/transfers/**
          filters:
            - name: AuthenticationFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG